<template>
  <div class="home">
    <drop-down :options="options" @continueAction="setSelected"/>
    <div class="main">
      <CharacterGraph :characaters="characters"/>
      <BottomBar :book="book"/>
    </div>
  
  </div>
</template>

<script setup>
// @ is an alias to /src
import {ref, reactive, computed, onMounted, watch} from "vue";
import DropDown from '@/components/DropDown.vue';
import CharacterGraph from '@/components/CharacterGraph.vue';
import {getAllBooks, getSpecificBook} from "@/api/api";
import BottomBar from "@/components/BottomBar.vue";

const options =ref([
    "A agua profunda",
    "A Alma Nova",
    "A Casa do Saltimbanco",
    "A Casa dos Fantasmas - Volume IEpisodio do Tempo dos Francezes",
    "A Casa dos Fantasmas - Volume II\rEpisodio do Tempo dos Francezes",
    "A Chave do Enigma",
    "A cidade do vicio",
    "A Cidade e as Serras",
    "A correspondência de Fradique Mendesmemórias e notas",
    "A Divorciada",
    "A Engomadeira: Novela Vulgar Lisboeta",
    "A espada de AlexandreCorte profundo da questão do Homem-Mulher e Mulher-Homem",
    "A Filha do ArcediagoTerceira Edição",
    "A Filha do Cabinda",
    "A Gratidão",
    "A Guerra: Depoimentos de Herejes",
    "A guerrilha de Frei Simão: romance historico",
    "A Illustre Casa de Ramires",
    "A Intrusa",
    "A Lenda da Meia-Noite",
    "A Lucta Civil Brazileira e o Sebastianismo Portuguez",
    "A Mao e A Luva",
    "A menina Lisa",
    "A Morgadinha de Val-D'Amores/Entre a Flauta e a ViolaTheatro Comico de Camillo Castello Branco",
    "A Morgadinha dos Cannaviaes (Chronica da aldeia)",
    "A Morte de D. Ignez de Castro Cantata por Manoel Maria Barbosa du Bucage; A Que Se Ajunta o Episódio, Ao Mesmo Assumpto, do Immortal Luiz de Camões",
    "A Morte Vence",
    "A Neta do Arcediago",
    "A nossa Gente",
    "A Nuvem: Peça dramatica, em verso, com prologo, dois actos e epilogo",
    "A Pata da Gazella: romance brasileiro.",
    "A Primavera",
    "A Queda d'um Anjo: Romance",
    "A Relíquia",
    "A Senhora Viscondessa",
    "A Velhice do Padre Eterno",
    "A viagem da Índia: poemeto em dois cantos",
    "A virtude laureadaDrama Recitado no Theatro do Salitre",
    "Agulha em PalheiroQuinta edição",
    "Album chulo-gaiato ou collecção de receitas para fazer rir",
    "Alexandre Herculano",
    "Alexandre Herculano\rConferencia pública realizada no Atheneu Commercial de Lisboa, na noite de 15 de Julho de 1900",
    "Alguns homens do meu tempo: impressões litterarias",
    "Ambições: Romance",
    "Amor Crioulovida argentina",
    "Amor de Perdição: Memorias d'uma familia",
    "Amor de Salvação",
    "Amôres d'um deputado",
    "Annos de Prosa; A Gratido; O Arrependimento",
    "Ao Entardecer (Contos Varios)",
    "Apontamentos sobre a via de communicação do rio Madeira",
    "Aquela Família: Tipos, caricaturas e episódios provincianos",
    "As Cinzas de Camillo",
    "As Netas do Padre Eterno\rRomance original",
    "As Noites do Asceta",
    "Astucias de Namorada, e Um melodrama em Santo Thyrso",
    "Aves Migradoras",
    "Biographia do Padre José Agostinho de MacedoSeguida d'um catalogo alfabetico de todas as suas obras",
    "Cantos Sagrados",
    "Carlota Angela",
    "Christovam Colombo e o descobrimento da America",
    "Claridades do sul",
    "Comedia do Campo volume III (Scenas do Minho)",
    "Considerações sobre a Philosophia da Historia Litteraria Portugueza\r(a proposito d'alguns livros recentes)",
    "Contos",
    "Contos d'Aldeia",
    "Contos do Norte",
    "Contos e Lendas",
    "Contos e Phantasias",
    "Contos escolhidos de D. Antonio de Trueba",
    "Contos Paraenses",
    "Contos Phantasticossegunda edição correcta e ampliada",
    "Côrte na aldeia e noites de inverno (Volume I)",
    "Da terra à lua, viagem directa em 97 horas e 20 minutos",
    "Despedidas: 1895-1899",
    "Do que o fogo não queima",
    "Dom Casmurro",
    "Dôr e Luz(Versos de um seminarista)",
    "Effeitos do Hypnotismo",
    "Electra: Drama em cinco actos",
    "Elegias",
    "Entre o caffé e o cognac",
    "Esau e Jacob",
    "Estrellas Funestas",
    "Estrellas Propícias",
    "Eurico, o presbytero",
    "Fanny: estudo",
    "Fialho d'Almeida",
    "Flirts",
    "Flores do Campo",
    "Floresta de varios romances",
    "Four Plays of Gil Vicente",
    "Frei Luiz de Sousa",
    "Helena",
    "Historia de um beijo",
    "Historia diplomatica do Brazil: O Reconhecimento do Imperio",
    "Historia Pitoresca: Palavras e frases celebres",
    "Historias Sem Data",
    "Humus",
    "Idyllios á beira d'aguaRomance original",
    "Indice chronologico dos factos mais notaveis da Historia do Brasildesde seu descobrimento em 1500 até 1849",
    "Infelizes: Historias Vividas",
    "Iracema\rcom uma noticia biographica do auctor",
    "Judas: Romance lirico em quatro jornadas",
    "Julião e a Biblia",
    "Julio Diniz (Joaquim Guilherme Gomes Coelho) Esboço Biographico",
    "Lagrimas Abençoadas",
    "Lendas do sul",
    "Lendas e Narrativas (Tomo I)",
    "Lendas e Narrativas (Tomo II)",
    "Livro de Consolação: Romance",
    "Lupe",
    "Maldita Felicidade",
    "Manhãs de Cascaes",
    "Manuel de Moraes: Chronica do Seculo XVII",
    "Marilia de Dirceo",
    "Memorial de Ayres",
    "Memórias",
    "Memorias de um pobre diabo",
    "Memorias Posthumas de Braz Cubas",
    "Miniaturas Romanticas",
    "Miragaia: Romance Popular",
    "Mundanismos",
    "Musa Velha",
    "Na Guella do Leão",
    "Nas Cinzas",
    "Nervosos, Lymphaticos e Sanguineos",
    "Newton: Poema",
    "No Paiz dos Yankees",
    "Noites de Cintra",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 01 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 02 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 03 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 04 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 05 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 06 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 07 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 08 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 09 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 10 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 11 (de 12)",
    "Noites de insomnia, offerecidas a quem não póde dormir. Nº 12 (de 12)",
    "Nova Castro: tragedia",
    "Nova Sapho: Tragedia Extranha",
    "Novelas do Minho",
    "Novos contos4º volume da Comedia do Campo",
    "O amor offendido, e vingado",
    "O Annel Mysterioso, Scenas da Guerra Peninsular",
    "O Arrependimento",
    "O Assassino de Macario: Comedia em tres actos",
    "O Bem e o Mal: Romance",
    "O Bispo: Nova «Heresia», em verso",
    "O Carrasco de Victor Hugo José Alves",
    "O Christão novo\rRomance Historico do Seculo XVI",
    "O Claro Riso Medieval",
    "O Conde de S. Luiz",
    "O condemnado, drama em tres actos e quatro quadros;\rSeguido do drama em um acto, Como os anjos se vingam",
    "O crime do padre Amaro, scenas da vida devota",
    "O descobrimento do Brasil por Pedro Alvares Cabral",
    "O Descobrimento do Brazil\rPrioridade dos Portugueses no Descobrimento da America",
    "O Engeitado",
    "O Guarany: romance brazileiro, Vol. 1 (of 2)",
    "O Guarany: romance brazileiro, Vol. 2 (of 2)",
    "O Infante Navegador: Poemeto",
    "O Mysterio da Estrada de Cintra. Cartas ao Diário de Noticias",
    "O Olho de Vidro",
    "O poeta Chiado\r(Novas investigações sobre a sua vida e escriptos)",
    "O presbyterio da montanha",
    "O Primo Bazilio: Episodio Domestico",
    "O que fazem mulheres: Romance philosophico",
    "O Regicida",
    "O Renegado a António Rodrigues Sampaio\rcarta ao Velho Pamphletario sobre a perseguição da imprensa",
    "O Romance d'uma cantora",
    "O Romance de um Homem Rico",
    "O vinho do Porto: processo de uma bestialidade ingleza\rexposição a Thomaz Ribeiro",
    "Obras Completas de Luis de Camões, Tomo II",
    "Obras Completas de Luis de Camões, Tomo III",
    "Obras poéticas de Nicoláo Tolentino de Almeida, Tom. II",
    "Opúsculos por Alexandre Herculano - Tomo 01",
    "Opúsculos por Alexandre Herculano - Tomo 02",
    "Opúsculos por Alexandre Herculano - Tomo 03",
    "Opúsculos por Alexandre Herculano - Tomo 04",
    "Opúsculos por Alexandre Herculano - Tomo 05",
    "Opúsculos por Alexandre Herculano - Tomo 06",
    "Opúsculos por Alexandre Herculano - Tomo 07",
    "Opúsculos por Alexandre Herculano - Tomo 08",
    "Opúsculos por Alexandre Herculano - Tomo 09",
    "Orpheu Nº1\rRevista Trimestral de Literatura",
    "Os Bravos do Mindello\rRomance Historico",
    "Os contos do tio Joaquim",
    "Os deputados brasileiros nas Côrtes Geraes de 1821",
    "Os descobrimentos portuguezes e os de Colombo: Tentativa de coordenação historica",
    "Os fidalgos da Casa Mourisca\rChronica da aldeia",
    "Os Filhos do Padre Anselmo",
    "Os Lusíadas",
    "Os Maias",
    "Os meus amores: contos e balladas",
    "Os netos de Camillo",
    "Os Pobres\rPrecedido de uma Carta-Prefacio de Guerra Junqueiro",
    "Os Primeiros Amores de Bocage\rComedia em Cinco Actos",
    "Os sonetos completos de Anthero de Quental",
    "Os Trabalhadores do Mar",
    "Os tripeiros\rromance-chronica do seculo XIV",
    "Papeis Avulsos",
    "Pátria",
    "Pelo mundo fóra",
    "Pero da Covilhan: Episodio Romantico do Seculo XV",
    "Poesias",
    "Poesias Completas",
    "Poesias Eroticas, Burlescas, e Satyricas de M.M. de Barbosa du Bocage\rnão comprehendidas na edição que das obras d'este poeta se publicou em Lisboa, no anno de MDCCCLIII.",
    "Poetas do Minho I - João Penha",
    "Portugal e Brazil: emigração e colonisação",
    "Portugal enfermo por vicios, e abusos de ambos os sexos",
    "Pranto de Maria Parda\rPorque vio as ruas de Lisboa com tão poucos ramos nas tavernas, e o vinho tão caro e ella não podia passar sem elle",
    "Quatro Novelas",
    "Quincas Borba",
    "Raios de extincta luz\rpoesias ineditas (1859-1863)",
    "Ramalho Ortigão",
    "Ramo de Floresacompanhado de varias criticas das Flores do Campo",
    "Reliquias de Casa Velha",
    "Robur, o Conquistador",
    "Romanceiro I: Romances da Renascença",
    "Romanceiro III: Romances Cavalherescos Antigos",
    "Ruy o escudeiro: Conto",
    "Sá de Miranda\rCom uma carta ácerca da \"Bibliographia Camilliana\" de Henrique Marques",
    "Sá de Miranda e a sua Obra",
    "Saudades: história de menina e moça",
    "Scenas Contemporaneas",
    "Scenas da Aldeia",
    "Scenas da Foz",
    "Scenas da Roça: Poema de costumes nacionaes",
    "Scenas de viagem\rExploração entre os rios Taquary e Aquidauana no districto de Miranda : memoria descriptiva",
    "Serão inquieto : contos",
    "Sinapismos",
    "Só",
    "Sol de Invernoultimos versos : 1915",
    "SurprezaEntre-acto original",
    "Talitha: evangelho em tres actos",
    "Theatro de João d'Andrade Corvo - IO Alliciador - O Astrologo",
    "Theóphilo Braga e a lenda do Crisfal",
    "Tractado da terra do Brasilno qual se contem a informação das cousas que ha nestaspartes feito por P.º de Magalhaes",
    "Transviado",
    "Tres capitaes",
    "Triste Fim de Polycarpo Quaresma",
    "Trovas do Bandarra\rnatural da Villa de Trancoso, apuradas e impressas por ordem de um grande senhor de Portugal",
    "Trovas Inedìtas de Bandarra",
    "Ubirajara: Lenda Tupi",
    "Um novo mundo",
    "Uma família ingleza: Scenas da vida do Porto",
    "Uma visita ao primeiro romancista portuguez em S. Miguel de Seide",
    "Versos de Bulhão Pato",
    "Viagem ao norte do Brazil feita nos annos 1613 a 1614, pelo Padre Ivo D'Evreux",
    "Viagens na Minha Terra (Completo)",
    "Viagens na Minha Terra (Volume I)",
    "Viagens na Minha Terra (Volume II)",
    "Villa Nova de Gaia",
    "Vinte Annos de Vida Litteraria",
    "Viriatho: Narrativa epo-historica",
    "Voltareis ó Christo?",
    "Yayá Garcia"
]);
const book = ref({});
const characters = ref([]);
watch(book, (incoming, prev) => {
    characters.value = incoming.characters;
});

const setSelected = async (val) =>{
  try{
    let res = await getSpecificBook(val)
    book.value = res.data;
  }
  catch(error)
  {
    console.log()
  }

}
</script>
<style scoped>
.main{
  display: flex;
  flex-direction: column;
  justify-content: space-between;

}
</style>
